### ISSUE TITLE
Error Merging JSON Files

### ISSUE THREAD

**Issue by DrorWalt** [cjbarrie/twittterv2r#4]
Can't merge saved JSON files. 
Error report: "Error: Argument 3 can't be a list containing data frames" when running loop starting with "for (i in seq_along(files)) {". 
Error stems from the line:   "df.all <- bind_rows(df.all, df)"

**Comment by cjbarrie** [comment]
Hey: could you give a worked example of the code your're using?

**Comment by DrorWalt** [comment]
library(httr)
library(tidyverse)
library(jsonlite)

get_tweets <- function(q="",n=10,start_time,end_time,token,next_token=""){
  if(n>500){
    warning("n too big. Using 500 instead")
    n <- 500
  }
  if(n<5){
    warning("n too small Using 10 instead")
    n <- 500
  }
  if(missing(token)){
    stop("bearer token must be specified.")  
  }
  if(missing(end_time)){
    end_time <- gsub(" ","T",paste0(as.character(Sys.time()),"Z"))
  }
  if(missing(start_time)){
    start_time <- paste0(Sys.Date(),"T00:00:00Z")
  }
  if(substr(token,1,7)=="Bearer "){
    bearer <- token
  } else{
    bearer <- paste0("Bearer ",token)
  }
  #endpoint
  url <- "https://api.twitter.com/2/tweets/search/all"
  #parameters
  params = list(
    "query" = q,
    "max_results" = n,
    "start_time" = start_time,
    "end_time" = end_time, 		
    "tweet.fields" = "attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,public_metrics,possibly_sensitive,referenced_tweets,source,text,withheld",
    "user.fields" = "created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,public_metrics,url,username,verified,withheld",
    "expansions" = "author_id,entities.mentions.username,geo.place_id,in_reply_to_user_id,referenced_tweets.id,referenced_tweets.id.author_id",
    "place.fields" = "contained_within,country,country_code,full_name,geo,id,name,place_type"
  )
  if(next_token!=""){
    params[["next_token"]] <- next_token
  }
  r <- httr::GET(url,httr::add_headers(Authorization = bearer),query=params)
  
  #fix random 503 errors
  count <- 0
  while(httr::status_code(r)==503 & count<4){
    r <- httr::GET(url,httr::add_headers(Authorization = bearer),query=params)
    count <- count+1
    Sys.sleep(count*5)
  }
  
  if(httr::status_code(r)!=200){
    stop(paste("something went wrong. Status code:", httr::status_code(r)))
  }
  if(httr::headers(r)$`x-rate-limit-remaining`=="1"){
    warning(paste("x-rate-limit-remaining=1. Resets at",as.POSIXct(as.numeric(httr::headers(r)$`x-rate-limit-reset`), origin="1970-01-01")))
  }
  dat <- jsonlite::fromJSON(httr::content(r, "text"))
  dat
}

#create folders for storage
ifelse(!dir.exists(file.path("data/")),
       dir.create(file.path("data/"), showWarnings = FALSE),
       FALSE)
ifelse(!dir.exists(file.path("includes/")),
       dir.create(file.path("includes/"), showWarnings = FALSE),
       FALSE)

#store bearer token for Academic product track v2
bearer_token = "<mytoken>"


#get tweets
start_tweets = "2020-12-01T07:00:00Z"
end_tweets = "2020-12-01T07:30:00Z"
nextoken <- ""
query <- "Obama"

while (!is.null(nextoken)) {
  df <-
    get_tweets(
      q = query ,
      n = 500,
      start_time = start_tweets,
      end_time = end_tweets,
      token = bearer_token,
      next_token = nextoken
    )
  jsonlite::write_json(df$data, paste0("data/", "data_", df$data$id[nrow(df$data)], ".json"))
  #jsonlite::write_json(df$includes,
  #                     paste0("includes/", "includes_", df$data$id[nrow(df$data)], ".json"))
  nextoken <-
    df$meta$next_token #this is NULL if there are no pages left
  cat(query, ": ", "(", nrow(df$data), ") ", "\n", sep = "")
  Sys.sleep(3.1)
  if (is.null(nextoken)) {
    cat("next_token is now NULL for", query, ": finishing collection.")
    break
  }
}

#parse and bind
files <-
  list.files(
    path = file.path("data/"),
    recursive = T,
    include.dirs = T
  )
files <- paste("data/", files, sep = "")

pb = txtProgressBar(min = 0,
                    max = length(files),
                    initial = 0)


df.all <- data.frame()
for (i in seq_along(files)) {
  filename = files[[i]]
  df <- read_json(filename, simplifyVector = TRUE)
  df.all <- bind_rows(df.all, df)
  setTxtProgressBar(pb, i)
}

**Comment by DrorWalt** [comment]
The issue only pop up at the before last line "df.all <- bind_rows(df.all, df)"

**Comment by DrorWalt** [comment]
Update: Solved by updating jsonlite/httr/dplyr packages.
